package output

import (
	"encoding/json"
	"fmt"
)

// Extending the autogenerated output structs.

// Create an alias for the entire struct.
type Output = SemgrepOutputV1Jsonschema

// Deserialize the JSON output to a Go struct.
func Deserialize(data []byte) (Output, error) {
	var out Output
	if err := out.UnmarshalJSON(data); err != nil {
		return out, fmt.Errorf("failed to deserialize Semgrep's output: %w", err)
	}
	return out, nil
}

// Serialize the Go struct to JSON. If beautify is true, the output is indented.
func (o Output) Serialize(beautify bool) ([]byte, error) {
	if beautify {
		return json.MarshalIndent(o, "", "  ")
	}
	return json.Marshal(o)
}

// ------

// RuleID returns the rule ID of a match/hit/result as a string.
func (c CliMatch) RuleID() string {
	return string(c.CheckId)
}

// FilePath returns the file path of a match/hit/result as a string.
func (c CliMatch) FilePath() string {
	return string(c.Path)
}

// Return the message of a match/hit/result as a string.
func (c CliMatch) Message() string {
	return c.Extra.Message
}
